[project]
name = "vendingmachine"
version = "0.1.0"
description = "My attempt at Guy Royse's vending machine kata."
requires-python = ">=3.14"
dependencies = [
    "getchar>=2.0.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
